name: fe-buildandpush-development

on:
  push:
    branches:
      - main

jobs:
  build-react-app:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source code
        id: checkout-code
        uses: actions/checkout@v2
 
