name: Matrix
on: push


jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ununtu-latest, windows-latest]
        node_version: [6, 8, 10] #this job run three times on all version sepratly 
        exclude:
          - os: ubuntu-latest
            node_ version: 6 #want to exclude job when os will be ubuntu-latest & version will be 6
          - os: macos-latest
            node_ version: 8 #want to exclude job when os will be macos-latest & version will be 8
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Node Version
        run: node -v
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log Node Version
        run: node -v
